export class ReceiverID {
  public static RECEIVER_ID_SHOW_MEMBERS: string = 'receiver_id_show_members';
  public static RECEIVER_ID_REPORT_TABLE: string = 'RECEIVER_ID_REPORT_TABLE';
  public static RECEIVER_ID_CLIENT_SEARCH_TABLE: string = 'RECEIVER_ID_CLIENT_SEARCH_TABLE';
  public static RECEIVER_ID_CURRENCY: string = 'receiver_id_currency';

  public static RECEIVER_ID_SHOW_MESSAGE: string = 'receiver_id_show_message';
  public static RECEIVER_ID_REFRESH_HOME_COMPONENT: string = 'RECEIVER_ID_REFRESH_HOME_COMPONENT';
  public static RECEIVER_ID_THOUSAND_FORMAT: string = 'receiver_id_thousand_format';
  public static RECEIVER_ID_SPINNER: string = 'RECEIVER_ID_SPINNER';
  public static RECEIVER_ID_FETCH_CLIENT: string = 'RECEIVER_ID_FETCH_CLIENT';
  public static RECEIVER_ID_FETCH_BY_CLIENT: string = 'RECEIVER_ID_FETCH_BY_CLIENT';
  public static RECEIVER_ID_FETCH_REPORT_IN_PROCESS: string = 'RECEIVER_ID_FETCH_REPORT_IN_PROCESS';
  public static RECEIVER_ID_FETCH_REPORT_IN_CREATION: string = 'RECEIVER_ID_FETCH_REPORT_IN_CREATION';
  public static RECEIVER_ID_REFRESH_TYPE_OF_CREDIT_DATA: string = 'RECEIVER_ID_REFRESH_TYPE_OF_CREDIT_DATA';
  public static RECEIVER_ID_REFRESH_PLACEMENT_TYPE_DATA: string = 'RECEIVER_ID_REFRESH_PLACEMENT_TYPE_DATA';
  public static RECEIVER_ID_REFRESH_CODEBOOK_DATA: string = 'RECEIVER_ID_REFRESH_CODEBOOK_DATA';
  public static RECEIVER_ID_LOAD_GROUP_DATA: string = 'RECEIVER_ID_LOAD_GROUP_DATA';

  public static RECEIVER_ID_REPORT_IN_PROGRESS_DATA: string = 'RECEIVER_ID_REPORT_IN_PROGRESS_DATA';
  public static RECEIVER_ID_DELETE_REPORT_IN_PROGRESS_WITH_ID: string = 'RECEIVER_ID_DELETE_REPORT_IN_PROGRESS_WITH_ID';
  public static RECEIVER_ID_SET_GROUP_TITLE: string = 'RECEIVER_ID_SET_GROUP_TITLE';

}
